version: '2'

services:
  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/php-fpm:latest
    ports:
      - 9000:9000
    volumes:
      - .:/app
